### ISSUE TITLE
ZapLine improvements

### ISSUE THREAD

**Issue by nbara** [nbara/python-meegkit#50]
### Todo:
- [x] Write ZapLine example --> see #52 
- [ ] data from #47 was really slow to run; Make ZapLine faster
- [x] Implement : https://github.com/maciekszul/zapline_iterator  (cc @maciekszul) --> see #52 
- [ ] Check out Zapline-plus : https://www.biorxiv.org/content/10.1101/2021.10.18.464805v1 (cc @MariusKlug )

**Comment by maciekszul** [comment]
i'm refactoring and improving the algo right now as it was a quick and dirty way to do the job. i should push something ready to use soon. my implementation of fitting relies on psd calculation. currently my code uses the [psd_array_multitaper](https://github.com/mne-tools/mne-python/blob/f71b98a3a082a79a89e0e5948813fbd7a27fdb66/mne/time_frequency/multitaper.py#L365) from mne. any suggestions how to go about that issue? not really keen on implementing a new psd calculation.

**Comment by nbara** [comment]
Awesome ! 

> currently my code uses the psd_array_multitaper from mne. any suggestions how to go about that issue? not really keen on implementing a new psd calculation.

Mmh not sure I want to add a dependency to MNE-python. 

That said, computing a PSD is easy enough and I'm sure we can find an easy replacement with scipy. I suggest you go ahead and open an pull request, and we can find a solution then.

**Comment by maciekszul** [comment]
> Mmh not sure I want to add a dependency to MNE-python.
i thought so :smile: 
i'll use [scipy.signal.welch](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.welch.html) then.

**Comment by nbara** [comment]
That would be great thanks. But I can also code that bit myself if you're short on time.

**Comment by maciekszul** [comment]
> I can also code that bit myself if you're short on time.

no worries. i can put together a quick bodge.

**Comment by malcolmudeozor** [comment]
Hi! Thanks so much for bringing ZapLine to Python. Super great tool. I see in your Todo checklist, you have a note about ZapLine-plus. Have you or are you planning to implement this update into Meegkit?

**Comment by nbara** [comment]
Hey @malcolmudeozor , no I haven't got around to implementing it. 

To be honest, I'm not sure I ever will because `dss_line_iter()` does the job for me.

**Comment by malcolmudeozor** [comment]
Thats great. I also enjoy using DSS iter because of its simplicity. However, I don't quite understand why it's not performing multiple iterations with my current data set. Do you mind me sending my example? Thank you!

**Comment by maciekszul** [comment]
Hi [malcolmudeozor](https://github.com/malcolmudeozor) you need to look at the PSD of your data. On noisy data, infant EEG for example, the window for the target frequency had to be widen. Look at the appropriate arguments in the function `win_sz=10, spot_sz=2.5`. From my experience, `spot_sz` has to be widen because the e.g. line noise is wider. Default values were suitable for best quality MEG.
